#! /usr/bin/ruby
require '~/Scripts/prompt' # absolute path required to work (for some reason)

# Exit early if a file name hasn't been provided
if ARGV.length < 1 then
    puts "Please provide at least one identifier"
    exit
end

# Gets all the strings that include the provided identifier(s)
matches = ARGV.map { |arg| Dir.entries('.').find_all { |str| str.include? arg}}.flatten

# If no identifiers match, just exit
if matches.count == 0 then
    puts "No entries matched the queries #{ARGV}"
    exit
end

# Shows the user which files it found
for file in matches do
    puts "Found #{file}."
end

# Prompt the user for whether or not they wish to delete the files
prompt("Do you wish to delete #{matches.count} files? [Y/n] ") do |answer|
    answer.downcase!
    case answer
    when "y", "yes" then
        # Iterate through the array of matches and remove them
        matches.each do |file| 
            unless File.directory?(file) then
                File.delete file
                puts "#{file} has been deleted."
            end
        end
    else 
        puts "Okay, nothing's been deleted."
    end
end